l_english:
 house_traditions_settings_decision:0 "가문 전통 모드 설정"
 house_traditions_settings_decision_tooltip:0 "가문 전통 모드(House Traditions Mod) 설정을 위해 메뉴를 열기"
 house_traditions_settings_decision_desc:0 "가문 전통 모드 설정 메뉴 열기"
 house_traditions_settings_effect_1:0 "지금은 '다른 가문과의 결혼 적합성 계산'에 대한 설정만 존재합니다."
 house_traditions_settings_decision_confirm:0 "메뉴 열기"

 house_trad_settings.0001.t:0 "가문 전통 모드 설정"
 house_trad_settings.0001.desc:0 "가문 전통 모드(House Traditions Mod) 설정입니다. 지금은 '다른 가문과의 결혼 적합성 계산'에 대한 설정만 존재합니다. 이는 '배우자 찾기' 기능에서 간헐적으로 성능 문제가 야기되기 때문입니다. 가문들은 자신의 전통에 걸맞는 결혼을 하려고 시도합니다. 예를 들어, 명예 전통의 인물은 사치 전통의 인물과 결혼을 꺼려할 것입니다. 이 기능을 끄는 것은 위신만을 바라보며 무작위적으로 결혼하는 바닐라 AI를 사용하도록 되돌아갑니다. 그러니 부디 성능 문제가 있을 경우에만 설정값을 해제하길 권장드립니다.\n\n현재 설정에 만족하고 앞으로 이 설정에 변화가 없을 경우, 본 설정 메뉴를 영구적으로 숨겨 더이상 결단 메뉴를 차지하지 않도록 할 수 있습니다."

 house_trad_settings.0001.on_desc:0 "결혼 적합성 계산의 현재 상태 #P ON#."
 house_trad_settings.0001.off_desc:0 "결혼 적합성 계산의 현재 상태 #N OFF#."

 house_trad_settings.0001.on:0 "결혼 적합성 계산을 활성화합니다"
 house_trad_settings.0001.off:0 "결혼 적합성 계산을 비활성화합니다"
 house_trad_settings.0001.hide:0 "앞으로 이 메뉴를 숨깁니다"
 house_trad_settings.0001.cancel:0 "닫기"
